appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: s3NJM1BUitCKXmnNMY+KVFegbT6P25kWWC9IC6TadPw8IS3fdbO8EpkBhjXkguMmmrSXEl/aCaK3348hodRRo+ph9NIG6hVYu6KQYsdHg2c9LlIh0/Hz4M9q+ldqQem4G47OGM5sZXWPFMFJYQgd1EwOgSGSCGYK7+xmXA8bdFdNOE55Hg2JCHXeNb/YBL3MulQfa32UYby9fpqVoX63gA3ffA/30rQNEoPhRMybK5pIKT5PcapL5kafN/xsPbxnkyT4Tlp97+3rx+B+/7+6z4pP4FhdzNLrMvxrAYfKtjXCU2DgmwohbC5TXCk70s8pFaCxZpVdItNZeIoj7VKt3JB5iT4FxTSoKOJS6HAttIUgvvuDlJHGToebrolGGNNDnxMBNl0cHNd/VlI/syMi+Thqat6FKTIae+RQSTvdTq2rRyoJdVkkW5WlzUOwDF7O7RqLOrElOWATGVsj+X0GJq1VadsPcdDcuSBnd1ZAGl4qpH8IhuByN1bXQjI0mhelLP20qr8I7YYd19wzTNx1PO1mmoSFi2VCxuw72ovRATltpzwqnCV4fOhlmsXw/MCN/KXtBNG5fUscqpeIqnJhe3nkGe5tUdkQ4csucIQhPytIKEDvPpf4841PTAw2QNf3pef4jO0HIQsjNPXahXJDaqlbW7LBBtbmgSbBnb566sc=}
